apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlapp
  template:
    metadata:
      labels:
        app: mlapp
    spec:
      containers:
        - name: mlapp
          image: YOUR_DOCKER_IMAGE_NAME
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mlapp-service
spec:
  selector:
    app: mlapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
